name: Tieba Sign-In

on:
  schedule:
    - cron: '0 22 * * *'  # 北京时间 06:00（UTC+8），对应 UTC 前一天 22:00
    - cron: '0 14 * * *'  # 北京时间 22:00（UTC+8），对应 UTC 14:00
  workflow_dispatch:      # 支持手动触发

jobs:
  signin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiotieba

      - name: Run Sign-In Script
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: |
          python Sign_In.py
